#![feature(plugin)]
#![allow(unstable)]
#![warn(missing_docs)]
#![plugin(docopt_macros)]
#![plugin(log)]
//! Watch files in a Cargo project and compile it when they change

extern crate "rustc-serialize" as rustc_serialize;
extern crate docopt;
#[no_link] extern crate docopt_macros;

extern crate notify;
#[macro_use] extern crate log;

use notify::{Error, RecommendedWatcher, Watcher};
use std::path::Path;
use std::sync::mpsc::channel;
use std::sync::Arc;

mod cargo;
mod compile;
mod ignore;
mod timelock;

docopt!(Args derive Debug, "
Usage: cargo-watch [options]
       cargo watch [options]

Options:
  -h, --help      Display this message
  -b, --build     Run `cargo build` when a file is modified
  -d, --doc       Run `cargo doc` when a file is modified
  -t, --test      Run `cargo test` when a file is modified
  -n, --bench     Run `cargo bench` when a file is modified

Default options are `build` and `test`
");

#[derive(Copy)]
struct Config {
    build: bool,
    doc: bool,
    test: bool,
    bench: bool
}

impl Config {
  fn new() -> Config {
    #![allow(unused_variables)]
    let Args {
      flag_build: mut build,
      flag_doc: doc,
      flag_test: mut test,
      flag_bench: bench,
      flag_help: _, // These three flags are not used. They are generated by docopt
      cmd_watch: _, // because both `cargo-watch` and `cargo watch` must be supported
      cmd_cargo: _ } = Args::docopt().decode().unwrap_or_else(|e| e.exit());

    if !build && !doc &&
      !test && !bench {
        // Default to build & doc
        build = true;
        test = true;
      }

    Config {
      build: build,
      doc: doc,
      test: test,
      bench: bench
    }
  }
}

fn main() {
  let config = Config::new();
  let (tx, rx) = channel();
  let w: Result<RecommendedWatcher, Error> = Watcher::new(tx);
  let mut watcher = match w {
    Ok(i) => i,
    Err(_) => {
      error!("Failed to init notify");
      std::os::set_exit_status(1);
      return;
    }
  };

  let t = timelock::new();
  let c = Arc::new(config);
  match cargo::root() {
    Some(p) => {
      let _ = watcher.watch(&p.join("src"));

      loop {
        match rx.recv() {
          Ok(e) => compile::handle_event(&t, e, c.clone()),
          Err(_) => ()
        }
      }
    },
    None => {
      error!("Not a Cargo project, aborting.");
      std::os::set_exit_status(64);
    }
  }
}
